server:
  port: 8081
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: limites-svc
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limites
    username: limite
    password: limite_passwd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

limite:
  valor: 2000

app:
  topic: transaction
  returnTopic: transaction_estorno

document:
  bucket-name: coffeeandit.spring.semolini

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key:
      secret-key:

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error